name: build magisk module and tag version

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: 'main'

jobs:
  update_version_and_build:
    runs-on: ubuntu-latest

    env:
      TZ: Pacific/Auckland  # Set the timezone to NZ/Auckland

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Version
        id: version
        run: |
          CURRENT_DATETIME=$(TZ=$TZ date +'%d.%m.%Y.%H.%M')
          NEW_VERSION="v${CURRENT_DATETIME}"
          echo "New Version: ${NEW_VERSION}"
          echo "::set-output name=new_version::${NEW_VERSION}"

      - name: Update module.prop
        run: |
          new_version="${{ steps.version.outputs.new_version }}"
          sed -i "s/version=.*/version=${new_version}/" magisk-module/module.prop

      - name: Commit and Push Changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add magisk-module/module.prop
          git commit -m "Bump version to ${{ steps.version.outputs.new_version }}"
          git push

      - name: Tagging
        run: |
          new_version="${{ steps.version.outputs.new_version }}"
          git tag "${new_version}"
          git push origin "${new_version}"

      - name: Get Commit SHA
        id: commit_sha
        run: |
          COMMIT_SHA=$(git rev-parse --short=5 HEAD)
          echo "::set-output name=commit_sha::${COMMIT_SHA}"

      - name: Update update.json with Commit SHA
        run: |
          new_version="${{ steps.version.outputs.new_version }}"
          commit_sha="${{ steps.commit_sha.outputs.commit_sha }}"
          zip_filename="S21U_p3s_csc_buildprop_magisk_module_${new_version}"
          sed -i "s|\"versionCode\": \".*\"|\"versionCode\": \"${commit_sha}\",|" magisk-module/update.json
          sed -i "s|\"zipUrl\": \".*\"|\"zipUrl\": \"https://github.com/AmirulAndalib/S21U-P3S-Exynos-Extras-OneUi/releases/download/${new_version}/${zip_filename}.zip\"|" magisk-module/update.json

      - name: Zip Magisk Module
        run: |
          cd magisk-module  # Change to the "magisk-module" folder

          new_version="${{ steps.version.outputs.new_version }}"
          zip_filename="S21U_p3s_csc_buildprop_magisk_module_${new_version}"

          zip -r "$zip_filename.zip" *

          ls -la && pwd

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.version.outputs.new_version }}"
          draft: false
          prerelease: false
          title: "Magisk Module for modded CSC and Build.prop release: ${{ steps.version.outputs.new_version }}"
          files: |
            /home/runner/work/S21U-P3S-Exynos-Extras-OneUi/S21U-P3S-Exynos-Extras-OneUi/magisk-module/*.zip
